server.port=8082

spring.application.name=vigicontrol

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/vigicontrolpro}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:260181}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=${JWT_SECRET:unaClaveSecretaMuyLargaYSeguraParaVigiControlPro2024}
jwt.expiration=${JWT_EXPIRATION:86400000}
# KAN-95: subida de fotos
app.upload.dir=uploads/incidents
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
